config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category' 

  get 'branding' => 'storefront#items_by_brand' 

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
end

app/models/category.rb
# category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :category
  belongs_to :brand
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :categories, :brands

  def categories
  	@categories = Category.order(:name)
  end

  def brands
  @brands = Product.pluck(:brand).sort.uniq
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
 def new
  @product = Product.new
  @categories = Category.all
end

def edit
  @categories = Category.all
end
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end

@brand = Brand.new(product_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand, :rating, :category_id, :image)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
 # @products = Product.where(category_id: params[:category_id])
 # @category = Category.find(params[:category_id]) 

def all_items
	@products = Product.all  
end

def items_by_category

  #to get to this page: catergorical_path(params[:category_id])

  @products = Product.where(category_id: params[:category_id])
  @category = Category.find(params[:category_id])

end

  def items_by_brand
    @products = Product.where(brand: params[:brand])
    @brand = params[:brand]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

<div class="form-group">
  <%= form.select :category_id, @categories.collect { |c| [ c.name, c.id ]}, {include_blank: "Please select a category" } %>
</div>

<div class="form-group">
  <strong>Upload Product Image: </strong>
  <%= form.file_field :image %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Rating</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.price %></td>ca
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.rating %></td>
        <td><%= product.category_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <div class="container">
    <%= yield %>
  </div>
<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storefront/all_items.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap 4 Website Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head><body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="#">
    <%= image_tag "hp-market.png",size: "50x50"%>
  </a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="#">About Us</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">FAQ</a>
    </li>

  <!-- Categories -->
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <% @categories.each do |category| %>
      <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
    <% end %>
       <li><%= link_to 'All', root_path %></li>
  </ul>
</li>
<!-- End Categories -->  

<!-- Brands -->
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <% @brands.each do |brand| %>
      <li><%= link_to brand, branding_path(brand: brand) %></li>
    <% end %>
      <li><%= link_to 'All', root_path %></li>
  </ul>
</li> 
<!-- End Brands -->   
    </li>
  </ul>
</nav>
<br>
  


<h1>Todays Deals</h1>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well">
        <% if product.image.url.nil? == false %>
          <p><%= image_tag product.image.url, size: 300 %></p>
        <% end %>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
         <p>
  <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
    <span class="glyphicon glyphicon-plus"></span> Quick Info
  </a>
</p>
          </a>
        </p>
      </div>
    </div>
    <div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
      </div>
      <div class="modal-body">
        <% if product.image.url.nil? == false %>
          <p><%= image_tag product.image.url, class: "storefront-pics" %></p>
        <% end %>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>made by <%= product.brand %></p>
      </div>
      <div class="modal-footer">
        <p>
          <!-- empty for now -->
        </p>
      </div>
    </div>
  </div>
</div>
  <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
</body>

app/views/storefront/items_by_brand.html.erb
<h1>Here are our <%= @brand %> products</h1>
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well center-it">
        <p><%= image_tag product.image.url(:thumb) %></p>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
          <a href='#' data-toggle="modal" data-target="#myModal_<%= product.id %>">
            <span class='glyphicon glyphicon-plus'></span>More Info
          </a>
        </p>
      </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title" id="myModalLabel"><%= product.name%></h4>
          </div>
          <div class="modal-body">
            <p><%= image_tag product.image.url(:thumb) %></p>
            <p><%= number_to_currency product.price %></p>
            <p><%= product.description %></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/storefront/items_by_category.html.erb
<h1>All of our <%= @category.name %></h1>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well center-it">
        <p><%= image_tag product.image.url %></p>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
          <a href='#' data-toggle="modal" data-target="#myModal_<%= product.id %>">
            <span class='glyphicon glyphicon-plus'></span>More Info
          </a>
        </p>
      </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title" id="myModalLabel"><%= product.name%></h4>
          </div>
          <div class="modal-body">
            <p><%= image_tag product.image.url %></p>
            <p><%= number_to_currency product.price %></p>
            <p><%= product.description %></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>